### ISSUE TITLE
Missmatched IP in VM using cloud-init than vCloud Director given IP

### ISSUE THREAD

**Issue by funky81** [terraform-providers/terraform-provider-vcd#510]
### Terraform Version
+ Terraform v0.12.24
+ provider.vcd v2.8.0

Your version of Terraform is out of date! The latest version
is 0.12.25. You can update by downloading from https://www.terraform.io/downloads.html

### Affected Resource(s)
vcd_vapp_vm
vcd_network_routed

### Terraform Configuration Files
```hcl
resource "vcd_vapp_vm" "vm-bastion" {
  count         = var.rancher_bastion_count 
  vapp_name     = "${vcd_vapp.rancher.name}"
  name          = "bastion"
  catalog_name  = "${data.vcd_catalog.ubuntu-catalog.name}"
  template_name = "${data.vcd_catalog_item.ubuntu-1804.name}" 
  memory        = 1024
  cpus          = 2
  cpu_cores     = 1

  metadata = {
    role    = "bastion"
    env     = var.raks_environment
  }
  
  guest_properties = {
    "user-data"        = local.base64-vm-bastion-userinit
    "hostname"         = "bastion"
  }

  network {
    type               = "org"
    name               = "${vcd_network_routed.net.name}"
    ip_allocation_mode = "MANUAL"
    is_primary         = true
    ip                 = "192.168.1.2"
  }
}

resource "vcd_network_routed" "net" {
  org = "${var.vcd_org}"
  vdc = "${var.vcd_vdc}"

  name         = "rancher-net"
  edge_gateway = "${data.vcd_edgegateway.rancher-edge.name}"
  gateway      = "192.168.0.1"
  netmask      = "255.255.0.0"
  dns1         = "202.152.0.2"
  dns2         = "202.152.5.36"

  static_ip_pool {
    start_address = "192.168.0.2"
    end_address   = "192.168.0.10"
  }

  static_ip_pool {
    start_address = "192.168.1.2"
    end_address   = "192.168.1.9"
  }

  dhcp_pool {
    start_address = "192.168.1.10"
    end_address   = "192.168.1.254"
  }
}
```
following is the [cloud init](https://gist.githubusercontent.com/funky81/df4627bcf2f8ea6d10e69ac06bb3f031/raw/b3be63e24f7437a9c88b49ac7e32d856ff9c042c/Bastion%2520Cloud-Init) script

### Debug Output
Following the file for [Logs for Terraform](https://gist.githubusercontent.com/funky81/53352766bc232dbfbd28228e90e28b4f/raw/33bdccd6b2438da17ef650330b0ab4e21402d2aa/tf.log) with following environment variables :
```shell
export TF_LOG_PATH=tf.log            
export TF_LOG=TRACE                  
export GOVCD_LOG_FILE=go-vcloud-director.log
export GOVCD_LOG=true     
```

### Expected Behavior
The VM obey the rules from vCloud Director especially from vcd_network_routed like in the above 
- [output from terraform](https://pasteboard.co/J9fJj2Q.png) - 192.168.1.2
- [output from vCloud Director  ](https://pasteboard.co/J9fKbKg.png) - 192.168.1.2
- [real in the vm](https://pasteboard.co/J9fKFcY.png) - 192.168.1.34

### Actual Behavior
Actual process from this creation is that, VM is using DHCP (cloud-init default) instead of vCloud Director given IP (Terraform script above is manual at 192.168.1.2)

### Steps to Reproduce
I only `terraform apply -auto-approve -parallelism=50` with above script to produce the bugs

**Comment by Didainius** [comment]
Hi @funky81,
I am afraid this is not an issue of `terraform-provider-vcd`. You should be able to see in Terraform the same IP that vCD UI is showing. 

It probably turns down to VM customization. As far as I looked (on ubuntu 20.04). cloud-init (DataSourceOvf) supports only a few variables and by default it tries to run open-vm-tools as well. However the bad news was that open-vm-tools in 20.04 looked for `ifconfig` (which is replaced with `ip`) to identify network adapter. It fails then and `/var/log/vmware-imc/toolsDeployPkg.log` has similar records:
<img width="832" alt="image" src="https://user-images.githubusercontent.com/15804230/82459794-02872b80-9ac1-11ea-8fa7-9b61080d2ca8.png">

After that - the adapter is just left as it is. 

As a workaround some people reported applying such `user-data` via `DataSourceOvf` however it gives the drawback that it doesn't really reflect vCD configuration value:

```yaml
#cloud-config
apt_reboot_if_required: False
package_update: True
package_upgrade: True
preserve_hostname: False
hostname: ${hostname}
fqdn: ${hostname}.${domain}
password: ${password}
chpasswd:
  expire: False
ssh_svcname: ssh
ssh_deletekeys: True
ssh_pwauth: False
ssh_genkeytypes: ['rsa', 'ed25519']
ssh_authorized_keys:
%{ for sshkey in sshkeys ~}
- ${sshkey}
%{ endfor ~}
write_files:
  - path: /etc/netplan/50-cloud-init.yaml
    content: |
      network:
        version: 2
        renderer: networkd
        ethernets:
          ens192:
            dhcp4: no
            addresses:
              - ${private}/20
            routes:
              - to: 0.0.0.0/0
                via: 10.10.0.11
                metric: 100
              - to: 0.0.0.0/0
                via: 10.10.0.12
                metric: 200
            nameservers:
              addresses:
                - 194.150.191.99
                - 194.8.57.12
runcmd:
  - [ netplan, apply ]
```


One more option I saw people exploring is https://github.com/vmware/cloud-init-vmware-guestinfo however I have not tested it myself so can't comment much.

**Comment by funky81** [comment]
Thanks @Didainius for your insight. Somehow I need to make it sync between terraform, vCloud Director and VM ip. Any idea except  [ https://github.com/vmware/cloud-init-vmware-guestinfo](https://github.com/vmware/cloud-init-vmware-guestinfo) since I havent explore much about this?

And I saw in your config, you put ${private}, is it possible to pass from terraform resource into user-data variables?

**Comment by Didainius** [comment]
It wasn't directly my sample, it was another user sharing his approach.

However yes - one should be able to pass vars



The above `user-data` yml was stored in `userdata.tmpl` and here is his snippet for usage using native Terraform templating engine:
```hcl
guest_properties = {
    "instance-id" = uuid()
    "hostname"    = "foobar"
    "password"    = "password"
    "user-data" = base64encode(templatefile("templates/userdata.tmpl", {
      hostname = "foobar",
      password = "password",
      domain   = var.domain,
      sshkeys  = var.sshkeys
    }))
  }
```

**Comment by funky81** [comment]
Thanks for this. Let me try for this one first. And also [https://github.com/vmware/cloud-init-vmware-guestinfo ](https://github.com/vmware/cloud-init-vmware-guestinfo ) I dont think it would work since it needs meta-data as the initial script

**Comment by Didainius** [comment]
@funky81 ,
If you find what works please share in this issue to serve as KB :)

Thanks!

**Comment by reski-rukmantiyo** [comment]
Hi @Didainius . The bugs only with VM with static IP configuration.

As last resort, i try what @Didainius recommend. Set VM (in terraform) with static IP which is the same like IP configure with cloud-init. This only works with static ip configuration. 

I still not have any solution for VM that is set with POOL in ip_allocation configuration (terraform)

**Comment by Didainius** [comment]
I am closing this for now, but feel free to re-open if you have any additional queries.
Would also be nice if you could share what solution you chose in the end for reference.

**Comment by reski-rukmantiyo** [comment]
Hi, 

I know this issue already close, but like you said, would be ok if I share the solution.
So here's my solution right now. Welcome for any new suggestions for this

- script for terraform

```
resource "vcd_vapp_vm" "vm" {
.....
  # setup for cloud init templates where the IP is taken from list of IP in the tfvars 
  guest_properties = {
    "hostname"         = "bastion"
    "user-data" = base64encode(templatefile("templates/bastion.tmpl", {
      ip =  "${element(var.vm_ips, count.index)}",
      ssh_keys = var.ssh_keys
    }))
  }

  # last but not least to make sure IP in the vCloud Director is the same like inside of the VM (although it's only for administration only)
  network {
    type               = "org"
    name               = "${vcd_network_routed.net.name}"
    ip_allocation_mode = "MANUAL"
    is_primary         = true
    ip                 = "${element(var.vm_ips, count.index)}"
  }
.....
}
````

- templates for cloud init
```
#cloud-config
.......
  - content: |
        network:
          version: 2
          renderer: networkd
          ethernets:
            ens192:
              addresses: [${ip}/24]
              gateway4: 192.168.0.1
              dhcp4: false
              nameservers:
                addresses: [2.52.80.2]
              optional: true
    path: /etc/netplan/50-cloud-init.yaml
.......
```
